import { Button, VerticalBox, Palette } from "std-widgets.slint";

export { TileViewer }from "tile-viewer.slint";
export { TileMapViewer }from "tilemap-viewer.slint";

enum KeyEventType { press, release }

struct KeyboardEvent {
    type: KeyEventType,
    event: KeyEvent,
}

struct RecentRom { index: int, path: string }

export component AppWindow inherits Window {
    callback load_rom();
    callback load_recent(int);
    callback toggle_playback();
    callback step_tick();
    callback embed_rom();

    callback toggle_tile_viewer();
    callback toggle_tilemap_viewer();
    callback toggle_memory_viewer();

    callback key_event(KeyboardEvent);

    callback dropped(DropEvent) -> DragAction;

    in-out property <bool> tile_viewer_shown: false;
    in-out property <bool> tilemap_viewer_shown: false;
    in-out property <bool> memory_viewer_shown: false;

    in-out property <bool> paused: true;
    in-out property <int> scale_factor: 2;
    in-out property <bool> show_fps: false;

    in-out property <bool> auto_scale: true;

    in property <[RecentRom]> recent;

    in property <float> fps: 0;
    in-out property <image> screen;

    function restore_focus() {
        key-handler.focus();
    }

    DropArea {
        can-drop(event) => DragAction.link;
        dropped(event) => dropped(event);
    }

    preferred-width: 1000px;
    preferred-height: 800px;

    in-out property <brush> default_background;

    background: {
        if self.full-screen {
            black
        }
        else {
            Palette.background;
        }
    };

    forward-focus: key-handler;

    key-handler := FocusScope {
        focus-lost(reason) => {
            debug("Lost focus ", reason);
        }

        capture-key-pressed(event) => {
            if !event.repeat {
                key_event({ event: event, type: KeyEventType.press });
            }
            accept
        }
        capture-key-released(event) => {
            if !event.repeat {
                key_event( { event: event, type: KeyEventType.release });
            }
            accept
        }
    }

    mouse_area := TouchArea { }

    MenuBar {
        visible: {
            if !root.full-screen {
                true
            }
            else {
                if mouse_area.mouse-y < 20px {
                    true
                }
                else {
                    false
                }
            }
        };
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("Load ROM");
                activated => {
                    load_rom()
                }
                shortcut: @keys(Control + O);
            }

            Menu {
                title: @tr("Recent");
                for recent-rom-entry in recent: MenuItem {
                    title: recent-rom-entry.index + 1 + ": " + recent-rom-entry.path;
                    activated => {
                        load_recent(recent-rom-entry.index)
                    }
                }
                for i in 5 - recent.length: MenuItem {
                    enabled: false;
                    title: "None";
                }
            }
        }

        Menu {
            title: @tr("Playback");
            MenuItem {
                title: @tr("Paused");
                checkable: true;
                checked <=> paused;
                activated => {
                    toggle_playback()
                }
                shortcut: @keys(Control + P);
            }

            MenuItem {
                title: @tr("Step Tick");
                activated => {
                    step_tick()
                }
                shortcut: @keys(Control + T);
            }
        }

        Menu {
            title: @tr("Video");
            MenuItem {
                title: @tr("Show FPS");
                checkable: true;
                checked <=> show_fps;
                activated => {
                }
            }

            MenuItem {
                title: @tr("Fullscreen");
                shortcut: @keys(Alt + Return);
                checkable: true;
                checked <=> root.full-screen;
                activated => {
                }
            }

            Menu {
                title: @tr("Video Scale");
                scaleAuto := MenuItem {
                    title: @tr("Auto");
                    checkable: true;
                    checked <=> auto_scale;
                    activated => {
                    }
                }

                MenuSeparator { }

                scale1x := MenuItem {
                    title: @tr("1x");
                    checkable: true;
                    checked: scale_factor == 1;
                    enabled: !auto_scale;
                    activated => {
                        scale_factor = 1;
                        scale1x.checked = true;
                        scale2x.checked = false;
                        scale3x.checked = false;
                        scale4x.checked = false;
                    }
                }

                scale2x := MenuItem {
                    title: @tr("2x");
                    checkable: true;
                    checked: scale_factor == 2;
                    enabled: !auto_scale;
                    activated => {
                        scale_factor = 2;
                        scale1x.checked = false;
                        scale2x.checked = true;
                        scale3x.checked = false;
                        scale4x.checked = false;
                    }
                }

                scale3x := MenuItem {
                    title: @tr("3x");
                    checkable: true;
                    checked: scale_factor == 3;
                    enabled: !auto_scale;

                    activated => {
                        scale_factor = 3;
                        scale1x.checked = false;
                        scale2x.checked = false;
                        scale3x.checked = true;
                        scale4x.checked = false;
                    }
                }

                scale4x := MenuItem {
                    title: @tr("4x");
                    checkable: true;
                    checked: scale_factor == 4;
                    enabled: !auto_scale;

                    activated => {
                        scale_factor = 4;
                        scale1x.checked = false;
                        scale2x.checked = false;
                        scale3x.checked = false;
                        scale4x.checked = true;
                    }
                }
            }
        }

        Menu {
            title: @tr("Tools");

            MenuItem {
                title: @tr("Embed ROM in PNG");
                activated => embed_rom();
            }

            MenuItem {
                title: @tr("Tile Viewer");
                checkable: true;
                checked <=> tile_viewer_shown;
                activated => toggle_tile_viewer();
            }

            MenuItem {
                title: @tr("Tile Map Viewer");
                checkable: true;
                checked <=> tilemap_viewer_shown;
                activated => toggle_tilemap_viewer();
            }

            MenuItem {
                title: @tr("Memory Viewer");
                checkable: true;
                checked <=> memory_viewer_shown;
                activated => toggle_memory_viewer();
            }
        }
    }

    HorizontalLayout {
        height: 100%;
        alignment: stretch;
        forward-focus: key-handler;

        screen_rect := Rectangle {
            min-width: auto_scale ? 160px : 160px * scale_factor;
            min-height: auto_scale ? 144px : 144px * scale_factor;
            clip: false;
            horizontal-stretch: 1;
            forward-focus: key-handler;

            Rectangle {
                in property <float> scale_factor: auto_scale ? floor(min(parent.width / 160px, parent.height / 144px)) : root.scale_factor;

                background: black;
                clip: true;
                width: 160px * scale_factor;
                height: 144px * scale_factor;
                horizontal-stretch: 1;

                Text {
                    horizontal-alignment: right;
                    stroke: black;
                    stroke-width: 2px;
                    visible: show_fps;
                    x: 0;
                    y: 0;
                    width: 100%;
                    text: fps.to-fixed(1);
                    z: 20;
                }

                screen_elem := Image {
                    forward-focus: key-handler;
                    x: 0;
                    y: 0;
                    width: 160px * scale_factor;
                    height: 144px * scale_factor;
                    image-fit: ImageFit.contain;
                    image-rendering: pixelated;
                    source <=> screen;
                }
            }
        }
    }
}
