import {
    AboutSlint,
    VerticalBox,
    GridBox,
    CheckBox,
    GroupBox,
    Slider,
    RadioGroup,
} from "std-widgets.slint";

export struct Tile {
    index: int,
    buffer: image,
}

enum TileMap { Background, Window }

export component TileMapViewer inherits Window {

    in-out property <TileMap> selected_map: Background;
    in-out property <{ x: float, y: float }> scroll;

    min-width: 500px;
    min-height: 500px;
    title: @tr("Tile Map Viewer");
    in-out property <[Tile]> tiles;

    DropArea { }

    HorizontalLayout {
        alignment: LayoutAlignment.stretch;
        VerticalBox {
            width: 200px;
            alignment: LayoutAlignment.start;
            horizontal-stretch: 0.1;
            GroupBox {
                RadioGroup {
                    title: @tr("Selected Map:");

                    RadioButton {
                        text: "Background";
                        checked: selected_map == TileMap.Background;
                        toggled => {
                            if self.checked { selected_map = TileMap.Background }
                        }
                    }

                    RadioButton {
                        text: "Window";
                        checked: selected_map == TileMap.Window;
                        toggled => {
                            if self.checked { selected_map = TileMap.Window }
                        }
                    }
                }
            }
        }

        Rectangle {
            clip: false;
            height: 100%;
            horizontal-stretch: 1;
            Rectangle {
                background: black;
                clip: true;
                height: max(floor(min(parent.width, parent.height) / 256px), 1.0) * 256px;
                width: max(floor(min(parent.width, parent.height) / 256px), 1.0) * 256px;

                for tile in tiles: Image {
                    x: floor(self.width / 1px * mod(tile.index, 32)) * 1px;
                    y: self.height * (floor(tile.index / 32));
                    width: 8 * parent.width / 256;
                    height: 8 * parent.height / 256;
                    source: tile.buffer;
                    image-rendering: pixelated;
                    TouchArea {
                        clicked => {
                            debug(parent.x, parent.y);
                        }
                    }
                }

                Rectangle {
                    x: scroll.x * parent.width / 256.0;
                    y: scroll.y * parent.height / 256.0;
                    width: 160 * parent.width / 256.0;
                    height: 144 * parent.height / 256.0;
                    border-color: magenta;
                    border-width: 1px;
                }

                Rectangle {
                    x: (scroll.x - 256) * parent.width / 256.0;
                    y: scroll.y * parent.height / 256.0;
                    width: 160 * parent.width / 256.0;
                    height: 144 * parent.height / 256.0;
                    border-color: magenta;
                    border-width: 1px;
                }

                Rectangle {
                    x: scroll.x * parent.width / 256.0;
                    y: (scroll.y - 256) * parent.height / 256.0;
                    width: 160 * parent.width / 256.0;
                    height: 144 * parent.height / 256.0;
                    border-color: magenta;
                    border-width: 1px;
                }

                Rectangle {
                    x: (scroll.x - 256) * parent.width / 256.0;
                    y: (scroll.y - 256) * parent.height / 256.0;
                    width: 160 * parent.width / 256.0;
                    height: 144 * parent.height / 256.0;
                    border-color: magenta;
                    border-width: 1px;
                }
            }
        }
    }
}
