name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: rui314/setup-mold@v1
    - uses: actions-use/setup-rust@stable
      with:
        # Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        toolchain: "nightly"
    - uses: taiki-e/install-action@v2
      with:
        tool: nextest
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -p gbemu_core --verbose
    - name: Run tests
      run: cargo nextest run -p gbemu_core --verbose --profile ci
      continue-on-error: true
    - name: Display test summary
      uses: test-summary/action@v2
      with:
        paths: "target/nextest/ci/junit.xml"
        show: "all"
        folded: true
  build-release-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: rui314/setup-mold@v1
    - uses: actions-use/setup-rust@stable
      with:
        # Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification
        toolchain: "nightly"
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -p gbemu_slint --verbose --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: gbemu
        path: ./target/release/gbemu_slint
    
      
      
